/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2018-12-13 04:25:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class AajPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta content=\"text/html\" charset=\"utf-8\">\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("   $('.map').click(function(){\r\n");
      out.write("      var name=$(this).attr('title');\r\n");
      out.write("      alert(name);\r\n");
      out.write("      //location.replace(\"detail.jsp\");\r\n");
      out.write("      //window.location.href = 'https://www.naver.com';\r\n");
      out.write("      window.location.href = 'http://www.google.com';\r\n");
      out.write("      //window.location.href=\"detail.jsp\";\r\n");
      out.write("   })\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("   function myfunction() {\r\n");
      out.write("   window.location.href=\"detail.jsp\";\r\n");
      out.write("   }\r\n");
      out.write("</script>\r\n");
      out.write("<title>ALL ABOUT JEONJU</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/NewFile.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"container\">\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "UserPage/header.jsp", out, false);
      out.write("\t\r\n");
      out.write("      <div id=\"map\" style=\"width: 600px; float: left;\">\r\n");
      out.write("         <h1 style=\"text-align: center\">관심있는 지역을 눌러보세요!</h1>\r\n");
      out.write("\r\n");
      out.write("         <img src='images/map.jpg' align=\"left\" border=\"0\" alt=\"\"\r\n");
      out.write("            usemap=\"#Map\">\r\n");
      out.write("         <map name=\"Map\">\r\n");
      out.write("            <area class=\"map\" target=\"_self\" title=\"효자동1가\" data-id=\"1\" href=\"\"\r\n");
      out.write("               onclick=\"myfunction();\" coords=\"378,425,440,440\" shape=\"rect\" />\r\n");
      out.write("            <area class=\"map\" target=\"_self\" title=\"효자동3가\" data-id=\"2\" href=\"\"\r\n");
      out.write("                coords=\"293,329,360,375\" shape=\"rect\" />\r\n");
      out.write("            <area class=\"map\" target=\"_self\" title=\"효자동2가\" data-id=\"3\" href=\"\"\r\n");
      out.write("               onclick=\"alert('test');\" coords=\"312,417,363,456\" shape=\"rect\" />\r\n");
      out.write("            <area class=\"map\" target=\"_self\" title=\"삼천동3가\" data-id=\"4\" href=\"\"\r\n");
      out.write("               onclick=\"alert('test');\"\r\n");
      out.write("               coords=\"245,441,277,444,304,475,305,511,274,501,251,471\"\r\n");
      out.write("               shape=\"poly\" />\r\n");
      out.write("         </map>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("      <div id=\"content\" style=\"background-color: white; float: center;\">\r\n");
      out.write("         <h1 style=\"text-align: center\">실시간 순위를 확인하세요!</h1>\r\n");
      out.write("      </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
