/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2018-12-22 06:23:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.UploadPage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class UplPgOnly_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta content=\"text/html\" charset=\"utf-8\">\r\n");
      out.write("<title>전주 mypage</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/uploadPage.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form action=\"UploadPage/upload.jsp\" method=\"post\">\r\n");
      out.write("    <img id=\"새로운 글쓰기\" src=\"images/writing.png\" width=\"40px\" height=\"40px\">&nbsp&nbsp새로운 글쓰기</img>\r\n");
      out.write("        <div class=\"ALL_wrap\">\r\n");
      out.write("                <div class=\"upload_wrap\">\r\n");
      out.write("                    <div id=\"photo-zone\">\r\n");
      out.write("                        <img id=\"box\" src=\"images/X-box.png\">\r\n");
      out.write("                        <input type=\"hidden\" id=\"box1\" name=\"box_all\" value=\"\" src=\"\" display=\"none\">\r\n");
      out.write("                        <input type=\"hidden\" id=\"box2\" name=\"box_all\" value=\"\" src=\"\" display=\"none\">\r\n");
      out.write("                        <input type=\"hidden\" id=\"box3\" name=\"box_all\" value=\"\" src=\"\" display=\"none\">\r\n");
      out.write("                        <input type=\"hidden\" id=\"box4\" name=\"box_all\" value=\"\" src=\"\" display=\"none\">\r\n");
      out.write("                        <input type=\"hidden\" id=\"box5\" name=\"box_all\" value=\"\" src=\"\" display=\"none\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"select-zone1\">\r\n");
      out.write("                        <img id=\"small_1\" src=\"\" display=\"none\" onclick=select_small(1)>\r\n");
      out.write("                        <img id=\"small_2\" src=\"\" display=\"none\" onclick=select_small(2)>\r\n");
      out.write("                        <img id=\"small_3\" src=\"\" display=\"none\" onclick=select_small(3)>\r\n");
      out.write("                        <img id=\"small_4\" src=\"\" display=\"none\" onclick=select_small(4)>\r\n");
      out.write("                        <img id=\"small_5\" src=\"\" display=\"none\" onclick=select_small(5)>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"select-zone\">\r\n");
      out.write("                        <table>\r\n");
      out.write("                            <tbody>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td>지역:</td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <select name=\"location\">\r\n");
      out.write("                                            <option>효자동1가</option>\r\n");
      out.write("                                            <option>효자동2가</option>\r\n");
      out.write("                                            <option>효자동3가</option>\r\n");
      out.write("                                        </select>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td>분야:</td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <select name=\"living\">\r\n");
      out.write("                                            <option>카페</option>\r\n");
      out.write("                                            <option>병원</option>\r\n");
      out.write("                                            <option>관광지</option>\r\n");
      out.write("                                            <option>미용실</option>\r\n");
      out.write("                                        </select>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </tbody>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"canvas_wrap\" >\r\n");
      out.write("                    <div id=canvas_head_wrap>\r\n");
      out.write("                        <label for=\"Uploading\"><img src=\"images/picture.png\"></label>\r\n");
      out.write("                        <input type=\"file\" id=\"Uploading\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"title_wrapper\">\r\n");
      out.write("                        <input name=\"title\" type=\"text\" placeholder=\"제목을 입력하세요.\">\r\n");
      out.write("                    </div><hr>\r\n");
      out.write("                    <div id=\"content_wrapper\">\r\n");
      out.write("                        <textArea name=\"content\" placeholder=\"내용을 입력하세요.\"></textArea> \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"bottom_wrap\">\r\n");
      out.write("                    <button id=\"submittt\">업로드!</button>\r\n");
      out.write("                </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        </form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
